version: '3.1'
volumes:
  nextcloud:
  db:
services:
  php:
    build: ./php
    ports:
      - "8081:80"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  phpmyadmin:
    image: phpmyadmin
    hostname: http://localhost:8080/
    restart: always
    links:
      - db
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1dok